version: "3"
services:
    server:
        container_name: admin-reassesment-server
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - mongo
        volumes: 
            - ./:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/frontend/node_modules
            - /usr/src/app/frontend/build
    mongo:
        image: mongo
        ports:
            - "27016:27017"
        volumes:
            - ./data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
            - MONG_INITDB_DATABASE=reassesment
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_BASICAUTH_USERNAME=nimish
            - ME_CONFIG_BASICAUTH_PASSWORD=nimishthegreat
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
        depends_on:
            - mongo
        ports:
            - "8888:8081"
    